In [3]:
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv("Crime.csv")
df

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
0,ANDHRA PRADESH,ADILABAD,2001,101,60,17,50,0,50,46,...,30,1131,16,149,34,175,0,181,1518,4154
1,ANDHRA PRADESH,ANANTAPUR,2001,151,125,1,23,0,23,53,...,69,1543,7,118,24,154,0,270,754,4125
2,ANDHRA PRADESH,CHITTOOR,2001,101,57,2,27,0,27,59,...,38,2088,14,112,83,186,0,404,1262,5818
3,ANDHRA PRADESH,CUDDAPAH,2001,80,53,1,20,0,20,25,...,23,795,17,126,38,57,0,233,1181,3140
4,ANDHRA PRADESH,EAST GODAVARI,2001,82,67,1,23,0,23,49,...,41,1244,12,109,58,247,0,431,2313,6507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9835,Lakshadweep,LAKSHADWEEP,2013,0,0,0,2,0,2,0,...,1,5,0,1,0,0,0,0,18,40
9836,Lakshadweep,ZZ TOTAL,2013,0,0,0,2,0,2,0,...,1,5,0,1,0,0,0,0,18,40
9837,Puducherry,KARAIKAL,2013,6,3,0,6,0,6,3,...,3,160,1,1,1,1,0,32,329,643
9838,Puducherry,PUDUCHERRY,2013,25,8,2,11,0,11,38,...,13,555,0,11,7,7,0,206,1464,3113
9839,Puducherry,ZZ TOTAL,2013,31,11,2,17,0,17,41,...,16,715,1,12,8,8,0,238,1793,3756

In [5]:
df.columns

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')

In [6]:
df=pd.read_csv("Crime.csv")

In [7]:
df.drop('CRIMINAL BREACH OF TRUST',axis=1,inplace=True)
df

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
0,ANDHRA PRADESH,ADILABAD,2001,101,60,17,50,0,50,46,...,30,1131,16,149,34,175,0,181,1518,4154
1,ANDHRA PRADESH,ANANTAPUR,2001,151,125,1,23,0,23,53,...,69,1543,7,118,24,154,0,270,754,4125
2,ANDHRA PRADESH,CHITTOOR,2001,101,57,2,27,0,27,59,...,38,2088,14,112,83,186,0,404,1262,5818
3,ANDHRA PRADESH,CUDDAPAH,2001,80,53,1,20,0,20,25,...,23,795,17,126,38,57,0,233,1181,3140
4,ANDHRA PRADESH,EAST GODAVARI,2001,82,67,1,23,0,23,49,...,41,1244,12,109,58,247,0,431,2313,6507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9835,Lakshadweep,LAKSHADWEEP,2013,0,0,0,2,0,2,0,...,1,5,0,1,0,0,0,0,18,40
9836,Lakshadweep,ZZ TOTAL,2013,0,0,0,2,0,2,0,...,1,5,0,1,0,0,0,0,18,40
9837,Puducherry,KARAIKAL,2013,6,3,0,6,0,6,3,...,3,160,1,1,1,1,0,32,329,643
9838,Puducherry,PUDUCHERRY,2013,25,8,2,11,0,11,38,...,13,555,0,11,7,7,0,206,1464,3113
9839,Puducherry,ZZ TOTAL,2013,31,11,2,17,0,17,41,...,16,715,1,12,8,8,0,238,1793,3756

In [8]:
df.columns

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CHEATING', 'COUNTERFIETING',
       'ARSON', 'HURT/GREVIOUS HURT', 'DOWRY DEATHS',
       'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')

In [17]:
df["CULPABLE HOMICIDE NOT AMOUNTING TO MURDER"].unique()

array([  17,    1,    2,    0,    7,    6,    4,   26,   12,    5,   14,
          3,   16,  136,    8,   40,   20,   11,   21,   18,   30,   10,
          9,   13,  250,   45,   60,   94,   78,   33,   53,  143,   74,
        111,   27,   28,  125,  101,   80,   63,   19,   23,   24,   15,
         25,   29,   36,   22,   37,   56, 1186,   38,   61,   75,   43,
         34,   44,  581,   31,  165,   55,   92,  396,   89,  115,   59,
         42,  210,   97,  194,   93,   58,   79,   68,   35, 1243,   47,
         62,   54,   32,  540,  147,   48,  298,   51,   76,  109,  343,
        203,  113,  138,  188,   39,   46, 1525,   50,  484,   65,  163,
        280,   57,  148,  473,   41, 1436,  468,   71,  117,  259,   87,
         88,  134,   98,   73,  216, 1520,  408,   64,  123,   83,  326,
        100, 1543,  401,  135,  257,   72,  155,  170, 1616,  394,  386,
        112,   81,   95,  204,   84,  146, 1493,  488,   66,  243,  104,
        129,   49, 1439,  241,  931,  344,   82,   86,  152,  120, 1401,
        179,  630,  171,  348,   85,  105,  139,  144, 1454,  126,  486,
        158,  285,  107,  114, 1410,  522, 1268,   52,  415])

In [18]:
df.drop('CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',axis=1,inplace=True)

In [19]:
df.columns

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER', 'RAPE',
       'CUSTODIAL RAPE', 'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CHEATING', 'COUNTERFIETING',
       'ARSON', 'HURT/GREVIOUS HURT', 'DOWRY DEATHS',
       'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')

In [ ]:
df.drop('CAUSING DEATH BY NEGLIGENCE',axis=1,inplace=True)

In [24]:
df.drop('ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',axis=1,inplace=True)

In [25]:
df.columns

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER', 'RAPE',
       'CUSTODIAL RAPE', 'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY', 'ROBBERY', 'BURGLARY',
       'THEFT', 'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CHEATING',
       'COUNTERFIETING', 'ARSON', 'DOWRY DEATHS', 'INSULT TO MODESTY OF WOMEN',
       'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES', 'OTHER IPC CRIMES',
       'TOTAL IPC CRIMES'],
      dtype='object')